version: '3'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/home/rails/turbo-potato
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
      - "15671:15671"
      - "5671:5671"
      - "4369:4369"  
  